### ISSUE TITLE
Prepare to release 0.9.5

### ISSUE THREAD

**Issue by nathanrice** [studiopress/genesis-tabs#19]
## Have you done the following in preparation for release?

- [ ] Bump version in all relevant and necessary locations.
- [ ] Create and execute db upgrade, if necessary.
- [ ] Build the styles/scripts if necessary (`npm run build`).
- [ ] Generate POT (`npm run makepot`).
- [ ] Verify CHANGELOG(s) has been updated.

**Comment by nickcernis** [comment]
Closing this as 0.9.5 has been released: https://github.com/studiopress/genesis-tabs/releases/tag/0.9.5
